[project]
name = "repl-nix-new-repl"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    
    "flask>=3.1.0",
    "openai==1.58.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
